### PR TITLE
Test for cronjob

### PR DESCRIPTION
**Pull request by recollir**
Adds a test for cronjobs and fixes the missing namespace variable in the hpa test.

### CODE REVIEW

**Comment by mhausenblas** [comment]
Excellent stuff, thank you again @recollir! We need to find a way to call out all your contributions. Will create some templates etc.

**Comment by recollir** [comment]
No worries. This is so little... but what are you’re plans for more? Any thoughts? Let’s have a beer in Seattle like we had in Munich during PromCon.

**Comment by mhausenblas** [comment]
Cool! So, plan is to sit together with Frederic later this week in Berlin to discuss the idea to turn `krs` into something like a lightweight Prometheus-on-the-CLI, supporting full PromQL. If you'd want to be part of this, please lemme know. Drinks at KubeCon sounds like a pretty good idea to me too ;)

**Comment by recollir** [comment]
Sounds interesting and cool. I would like to contribute. If I can.

**Comment by mhausenblas** [comment]
Awesome, will let you know on Friday then ;)

**Pull request merged**
